### PR TITLE
Hyperlink DOI to preferred resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
Same as https://github.com/matplotlib/matplotlib/pull/11470 ;-)

### CODE REVIEW

**Comment by katrinleinweber** [comment]
Are the failing tests due to my update? I find no mention of `doi` in the error logs and since the [last successful build is years old](https://travis-ci.org/matplotlib/trendvis/builds/130883607) I guess something about the environment changed in the meantime.

**Comment by tacaswell** [comment]
We no longer support any of those python versions in the latest version of Matplotlib which is likely the problem....

**Comment by tacaswell** [comment]
I am going to go ahead a merge this so it does not sit forever, thanks @katrinleinweber !

**Comment by katrinleinweber** [comment]
You're welcome, and thanks for merging :-)

**Pull request merged**
